/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppASpot {
        "image": string;
        "name": string;
        "smallText": boolean;
    }
    interface AppBlog {
    }
    interface AppBlogDetails {
    }
    interface AppClients {
    }
    interface AppFooter {
    }
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface AppToolCard {
        "tool": string;
    }
    interface AppWork {
    }
    interface AppWorkDetails {
        "match": MatchResults;
    }
}
declare global {
    interface HTMLAppASpotElement extends Components.AppASpot, HTMLStencilElement {
    }
    var HTMLAppASpotElement: {
        prototype: HTMLAppASpotElement;
        new (): HTMLAppASpotElement;
    };
    interface HTMLAppBlogElement extends Components.AppBlog, HTMLStencilElement {
    }
    var HTMLAppBlogElement: {
        prototype: HTMLAppBlogElement;
        new (): HTMLAppBlogElement;
    };
    interface HTMLAppBlogDetailsElement extends Components.AppBlogDetails, HTMLStencilElement {
    }
    var HTMLAppBlogDetailsElement: {
        prototype: HTMLAppBlogDetailsElement;
        new (): HTMLAppBlogDetailsElement;
    };
    interface HTMLAppClientsElement extends Components.AppClients, HTMLStencilElement {
    }
    var HTMLAppClientsElement: {
        prototype: HTMLAppClientsElement;
        new (): HTMLAppClientsElement;
    };
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppToolCardElement extends Components.AppToolCard, HTMLStencilElement {
    }
    var HTMLAppToolCardElement: {
        prototype: HTMLAppToolCardElement;
        new (): HTMLAppToolCardElement;
    };
    interface HTMLAppWorkElement extends Components.AppWork, HTMLStencilElement {
    }
    var HTMLAppWorkElement: {
        prototype: HTMLAppWorkElement;
        new (): HTMLAppWorkElement;
    };
    interface HTMLAppWorkDetailsElement extends Components.AppWorkDetails, HTMLStencilElement {
    }
    var HTMLAppWorkDetailsElement: {
        prototype: HTMLAppWorkDetailsElement;
        new (): HTMLAppWorkDetailsElement;
    };
    interface HTMLElementTagNameMap {
        "app-a-spot": HTMLAppASpotElement;
        "app-blog": HTMLAppBlogElement;
        "app-blog-details": HTMLAppBlogDetailsElement;
        "app-clients": HTMLAppClientsElement;
        "app-footer": HTMLAppFooterElement;
        "app-header": HTMLAppHeaderElement;
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-tool-card": HTMLAppToolCardElement;
        "app-work": HTMLAppWorkElement;
        "app-work-details": HTMLAppWorkDetailsElement;
    }
}
declare namespace LocalJSX {
    interface AppASpot {
        "image"?: string;
        "name"?: string;
        "smallText"?: boolean;
    }
    interface AppBlog {
    }
    interface AppBlogDetails {
    }
    interface AppClients {
    }
    interface AppFooter {
    }
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface AppToolCard {
        "tool"?: string;
    }
    interface AppWork {
    }
    interface AppWorkDetails {
        "match"?: MatchResults;
    }
    interface IntrinsicElements {
        "app-a-spot": AppASpot;
        "app-blog": AppBlog;
        "app-blog-details": AppBlogDetails;
        "app-clients": AppClients;
        "app-footer": AppFooter;
        "app-header": AppHeader;
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-tool-card": AppToolCard;
        "app-work": AppWork;
        "app-work-details": AppWorkDetails;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-a-spot": LocalJSX.AppASpot & JSXBase.HTMLAttributes<HTMLAppASpotElement>;
            "app-blog": LocalJSX.AppBlog & JSXBase.HTMLAttributes<HTMLAppBlogElement>;
            "app-blog-details": LocalJSX.AppBlogDetails & JSXBase.HTMLAttributes<HTMLAppBlogDetailsElement>;
            "app-clients": LocalJSX.AppClients & JSXBase.HTMLAttributes<HTMLAppClientsElement>;
            "app-footer": LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-tool-card": LocalJSX.AppToolCard & JSXBase.HTMLAttributes<HTMLAppToolCardElement>;
            "app-work": LocalJSX.AppWork & JSXBase.HTMLAttributes<HTMLAppWorkElement>;
            "app-work-details": LocalJSX.AppWorkDetails & JSXBase.HTMLAttributes<HTMLAppWorkDetailsElement>;
        }
    }
}
